Dev thaissa
Izabela-dsn/best-friend-back pull request #4
Opened 2023-11-22 01:25 UTC by crato-thaissa

2023-11-22 14:53 UTC, Izabela-dsn requested changes
Bem  feito, falta só alguns detalhes as serem retocados

2023-11-22 14:53 UTC, Izabela-dsn commented on src/main.py
> +        class_type = 'medicine-vaccine'
mudar o class_type para medVacc

2023-11-22 14:53 UTC, Izabela-dsn commented on src/main.py
> +        pet = session.query(Pets) #
pode retirar essa linha 261

2023-11-22 14:53 UTC, Izabela-dsn commented on src/main.py
> +
código duplicado da linha 275 até 278, retirar

2023-11-22 14:53 UTC, Izabela-dsn commented on src/main.py
> +        exam = session.query(Exams)
pode retirar linha 306

2023-11-22 14:53 UTC, Izabela-dsn commented on src/main.py
> +    try:
organizar essa função, o protocol_id é o id do medicine_vaccine eu troquei o nome para protocol por preguiça de escrever medicine_vaccine_id

2023-11-22 14:53 UTC, Izabela-dsn commented on src/main.py
> +
apagar comentários das funções que já foram feitas

2023-11-25 01:34 UTC, crato-thaissa commented
Second Commit

2023-11-25 01:34 UTC, closed without merging